language: generic
os:
# - linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: oSfx1/DJ58uiE96ckf31EmFXZ1PFkeYptylMYeaFJA22mQuaWnmo/Yxkma9SdOH3+KEoD+z8/ZmUgyPxPmQ3yT47BBx7bnfDzj4wyd9NLe95Z9m+AVXoE1IUZxcDJmm3Q1x2MVxAAYndLWR1/vuE1duj8uYMa0nzc1V6ZH7hyM8l+kpl2A8vKKtBKvrYnSmFe+JjwjdOGAqMSn/JUGBezbzkxwyvmtGHjZPwItf8LKSiYa1piQvF7obDPFcrR6DVUjCTOFUoNo90aeIr8DIIvBtaQv6oopL/dI0MQ8C7PxG4Kof1/f2ug/NgV2QVGyNTEHPOEQ06v7qYNnw64pY+BWn7OMGmWPF0dlhMXPojU8dLvvUWRdHCNq5+gqGkARJbDGHVoo6qE52Lwz/YF7CbIai7o4khD7VF7ObJL/ExF0ebxcu3z9DHls/BONBrBCe5gufMeqSQ9xsAs+pxFN3MbjsQShD5MWji52ZlBfFcAMwUDbjMzOdlrIIbplLySqUgy3c7ussj/pzTjzQf/usUYE2xe53vaKAcovRpaWfoOIPD7+X7sbdpupPo0KLq3LZt5Sdoc8AjA5f7mLvOSFa6+y4v+KrK4zWq1JBc9eYA1e6Nv/DiqhpDXSo+E8KrydQ+ytKwA7nfUh55SJSrm4AoJf6SAZdPTvmaCz73DFTX/ig=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack
  --token=-
